<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItem;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adding news block paragraph.
 */
function os2web_news_preprocess_paragraph__os2web_news_block(&$variables) {
  if ($variables['view_mode'] == 'preview') {
    return;
  }

  $paragraph = $variables['paragraph'];
  // Getting the related sections.
  $values = $paragraph->get('field_os2web_news_par_section')->getValue();

  if (!empty($values)) {
    $section_target_ids = array_column($values, 'target_id');
    $section_term_ids = implode(',', $section_target_ids);
    $variables['content'][] = views_embed_view('os2web_news', 'os2web_news_embed_limited', $section_term_ids);
  }
  else {
    $variables['content'][] = views_embed_view('os2web_news', 'os2web_news_embed_limited');
  }
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adding news block paragraph.
 */
function os2web_news_preprocess_paragraph__os2web_news_page(&$variables) {
  if ($variables['view_mode'] == 'preview') {
    return;
  }

  $paragraph = $variables['paragraph'];
  // Getting the related sections.
  $values = $paragraph->get('field_os2web_news_par_section')->getValue();

  if (!empty($values)) {
    $section_target_ids = array_column($values, 'target_id');
    $section_term_ids = implode(',', $section_target_ids);
    $variables['content'][] = views_embed_view('os2web_news', 'os2web_news_embed_page', $section_term_ids);
  }
  else {
    $variables['content'][] = views_embed_view('os2web_news', 'os2web_news_embed_page');
  }

}

/**
 * Callback for getting current time on field value.
 */
function os2web_news_get_current_datetime($entity, $definition) {
  if ($definition->getType() == 'timestamp') {
    return time();
  }
  elseif ($definition->getType() == 'datetime') {
    return [
      'default_date_type' => 'relative',
      'default_date' => 'now'
    ];
  }
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function os2web_news_entity_bundle_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node' && $bundle == 'os2web_news' && !empty($fields['field_os2web_news_article_date'])) {
    // Set default value callback.
    $fields['field_os2web_news_article_date']
      ->setDefaultValueCallback('os2web_news_get_current_datetime');
  }
}

/**
 * Implements hook_entity_presave().
 *
 * On a new node save copies header from title if header value is empty.
 */
function os2web_news_node_presave(NodeInterface $node) {
  if ($node->isNew() && $node->getType() == 'os2web_news') {
    // If header is empty, use the title.
    if (empty($node->field_os2web_news_heading->value)) {
      $node->field_os2web_news_heading->value = $node->label();
    }
  }
}


function os2web_news_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (!\Drupal::currentUser()->hasPermission('create paragraph content os2web_banner_paragraph')) {
    unset($form['field_os2web_news_paragraph_bann']);
  }

  if (!\Drupal::currentUser()->hasPermission('os2web_page access sideafsnit tab')) {
    unset($form['field_os2web_news_paragraph_left']); // sideafsnit tab
    unset($form['field_os2web_news_paragraph_righ']); // sideafsnit tab
  }

  if (!\Drupal::currentUser()->hasPermission('os2web_page access sidebygger tab')) {
    unset( $form['field_os2web_news_paragraph_wid'] ); // sidebygger tab
  }

  if (!\Drupal::currentUser()->hasPermission('os2web_page access media tab')) {
    unset( $form['field_os2web_news_primaryimage'] ); // media tab
  }

  if (!\Drupal::currentUser()->hasPermission('os2web_page access instillinger tab')) {
    // unset( $form['os2web_page access media tab'] ); // media tab
  }

}