
<?php

/**
 * @file
 * Install, uninstall and update hooks for page builder module.
 */

use Symfony\Component\Yaml\Yaml;

function os2web_news_read_in_new_config($config_name) {
  $path = drupal_get_path('module', 'os2web_news');
  /** @var \Drupal\Core\Config\StorageInterface $active_storage */
  $active_storage = \Drupal::service('config.storage');
  $active_storage->write($config_name, Yaml::parse(file_get_contents($path . '/config/optional/' . $config_name . '.yml')));
}
