<?php

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adding news block paragraph.
 */
function os2web_news_preprocess_paragraph__os2web_news_block(&$variables) {
  if ($variables['view_mode'] == 'preview') {
    return;
  }

  $variables['content'][] = views_embed_view('os2web_news', 'os2web_news_embed_limited');
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * Adding news block paragraph.
 */
function os2web_news_preprocess_paragraph__os2web_news_page(&$variables) {
  if ($variables['view_mode'] == 'preview') {
    return;
  }

  $variables['content'] = views_embed_view('os2web_news', 'os2web_news_embed_page');
}
