<?php

namespace Drupal\os2web_news\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Drupal\node\NodeInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Provides a 'OS2Web news notification block.
 *
 * @Block(
 *   id = "os2web_news_notification_block",
 *   admin_label = @Translation("OS2Web News Notification Block")
 * )
 */
class NewsNotificationBlock extends BlockBase
{

  /**
   * {@inheritdoc}
   */
  public function
  blockForm($form, FormStateInterface $form_state)
  {

    $form = parent::blockForm($form, $form_state);
    $config = $this->getConfiguration();

    // Path of search page.
    $form['notification_text'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Notification text'),
      '#default_value' => $config['notification_text'],
    ];

    $form['date_offset'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Date offset when notification is shown'),
      '#description' => 'An offset from the current time such as "-1 day" or "-3 months"',
      '#default_value' => empty($config['date_offset']) ? '-3 months' : $config['date_offset'],

    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function blockSubmit($form, FormStateInterface $form_state)
  {
    $this->setConfigurationValue('notification_text', $form_state->getValue('notification_text'));
    $this->setConfigurationValue('date_offset', $form_state->getValue('date_offset'));
  }

  public function build()
  {
    $config = $this->getConfiguration();
    $entity = \Drupal::routeMatch()->getParameter('node');
    // Check if it is not a node or node type is not os2web_news.
    if (!($entity instanceof NodeInterface) || $entity->getType() != 'os2web_news') {
      return [
        '#markup' => '',
      ];
    }
    // You also have the node object right here.
    $news_article_date = $entity->get('field_os2web_news_article_date')->getValue();
    if ((int)$news_article_date[0]['value'] <= strtotime($config['date_offset'])) {
      return [
        '#markup' => '<div data-drupal-messages="">
            <div role="contentinfo" class="messages messages--info">'
          . $config['notification_text'] . "</div></div>",
        '#cache' => ['max-age' => 0],
        '#attached' => [
          'library' => [
            'os2web_news/info-messages'
          ]
        ]
      ];
    } else {
      return [
        '#markup' => '',
      ];
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getCacheContexts()
  {
    // TODO: Change the autogenerated stub.
    $context = parent::getCacheContexts();
    $context[] = 'url.path';
    $context[] = 'url.query_args';
    return $context;
  }

}

